### ISSUE TITLE
Error spawning child process

### ISSUE THREAD

**Issue by arpunk** [pgte/fugue#4]
Every 2 hours or so I get the following error:

```
pipe(): Too many open files

child_process:212
var fds = this.fds = this._internal.spawn(path, args, cwd, envPairs, customF
                                    ^
Error: Error spawning
  at ChildProcess.spawn (child_process:212:39)
  at child_process:9:15
  at /export/services/node/lib/node/.npm/fugue/0.0.36/package/lib/fugue.js:320:48
  at ChildProcess.<anonymous> (/export/services/node/lib/node/.npm/fugue/0.0.36/package/lib/fugue.js:327:13)
  at ChildProcess.emit (events:27:15)
  at ChildProcess.onexit (child_process:168:12)
  at node.js:772:9
```

Im running node 0.2.4 with fugue 0.0.36 (it crashes on both OS X, Solaris, OpenSolaris and  OpenIndiana.

Heres some of the crashing times:

Nov  7 04:46:56 opensolaris svc.startd[9]: [ID 694882 daemon.notice] instance svc:/application/nodes/server:home exited with status 1
Nov  7 06:35:57 opensolaris svc.startd[9]: [ID 694882 daemon.notice] instance svc:/application/nodes/server:home exited with status 1
Nov  7 08:24:58 opensolaris svc.startd[9]: [ID 694882 daemon.notice] instance svc:/application/nodes/server:home exited with status 1
Nov  7 10:13:59 opensolaris svc.startd[9]: [ID 694882 daemon.notice] instance svc:/application/nodes/server:home exited with status 1
Nov  7 12:03:00 opensolaris svc.startd[9]: [ID 694882 daemon.notice] instance svc:/application/nodes/server:home exited with status 1
Nov  7 13:52:01 opensolaris svc.startd[9]: [ID 694882 daemon.notice] instance svc:/application/nodes/server:home exited with status 1
Nov  7 15:41:02 opensolaris svc.startd[9]: [ID 694882 daemon.notice] instance svc:/application/nodes/server:home exited with status 1
Nov  7 17:30:03 opensolaris svc.startd[9]: [ID 694882 daemon.notice] instance svc:/application/nodes/server:home exited with status 1
Nov  7 19:19:04 opensolaris svc.startd[9]: [ID 694882 daemon.notice] instance svc:/application/nodes/server:home exited with status 1
Nov  7 21:08:05 opensolaris svc.startd[9]: [ID 694882 daemon.notice] instance svc:/application/nodes/server:home exited with status 1
Nov  7 22:57:06 opensolaris svc.startd[9]: [ID 694882 daemon.notice] instance svc:/application/nodes/server:home exited with status 1
Nov  8 00:46:07 opensolaris svc.startd[9]: [ID 694882 daemon.notice] instance svc:/application/nodes/server:home exited with status 1
Nov  8 02:35:08 opensolaris svc.startd[9]: [ID 694882 daemon.notice] instance svc:/application/nodes/server:home exited with status 1
Nov  8 04:24:09 opensolaris svc.startd[9]: [ID 694882 daemon.notice] instance svc:/application/nodes/server:home exited with status 1
Nov  8 06:13:10 opensolaris svc.startd[9]: [ID 694882 daemon.notice] instance svc:/application/nodes/server:home exited with status 1
Nov  8 08:02:11 opensolaris svc.startd[9]: [ID 694882 daemon.notice] instance svc:/application/nodes/server:home exited with status 1
Nov  8 09:51:12 opensolaris svc.startd[9]: [ID 694882 daemon.notice] instance svc:/application/nodes/server:home exited with status 1
Nov  8 11:40:13 opensolaris svc.startd[9]: [ID 694882 daemon.notice] instance svc:/application/nodes/server:home exited with status 1

I can upload the whole service logs if you want.

**Comment by arpunk** [comment]
Sorry, didn't know there was already an issue opened for it.
